# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Episki < Formula
  desc "The official command-line interface for episki"
  homepage "https://episki.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/episki/episki-cli/releases/download/v1.0.0/episki_1.0.0_darwin_amd64.tar.gz"
      sha256 "52a9d220ae1b131d158012de433003b0cf9cd4113b0321db445aa39779360472"

      define_method(:install) do
        bin.install "episki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/episki/episki-cli/releases/download/v1.0.0/episki_1.0.0_darwin_arm64.tar.gz"
      sha256 "cb497a851b15f02dde68c169cca9f44b3da54344433363718e1bceda5a07b68e"

      define_method(:install) do
        bin.install "episki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/episki/episki-cli/releases/download/v1.0.0/episki_1.0.0_linux_amd64.tar.gz"
      sha256 "5e9f52875449bc3bc145313535ba0667f834eda6fa7b49aceecc018fcb1bcc1a"
      define_method(:install) do
        bin.install "episki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/episki/episki-cli/releases/download/v1.0.0/episki_1.0.0_linux_arm64.tar.gz"
      sha256 "c757b8288a4cb8c7ebadb82bd0fcfb8a1990de18f4d6603e639ac150a0c5f592"
      define_method(:install) do
        bin.install "episki"
      end
    end
  end

  test do
    system "#{bin}/episki", "--version"
  end
end
